function createfigure(XData1, XData2, YData1, XData3, YData2, XData4, YData3, XData5, YData4)
%CREATEFIGURE(XData1, XData2, YData1, XData3, YData2, XData4, YData3, XData5, YData4)
%  XDATA1:  line xdata
%  XDATA2:  line xdata
%  YDATA1:  line ydata
%  XDATA3:  line xdata
%  YDATA2:  line ydata
%  XDATA4:  line xdata
%  YDATA3:  line ydata
%  XDATA5:  line xdata
%  YDATA4:  line ydata

%  Auto-generated by MATLAB on 24-May-2021 20:47:11

% Create figure
figure1 = figure('Tag','PLOTROC1','NumberTitle','off',...
    'Name','Receiver Operating Characteristic (plotroc)');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData2,YData1,'Parent',subplot1,'LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('True Positive Rate');

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Training ROC');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 1]);
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'DataAspectRatio',[1 1 1]);
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData3,YData2,'Parent',subplot2,'LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('True Positive Rate');

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Validation ROC');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 1]);
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'DataAspectRatio',[1 1 1]);
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData4,YData3,'Parent',subplot3,'LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('True Positive Rate');

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Test ROC');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0 1]);
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'DataAspectRatio',[1 1 1]);
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot4,'LineWidth',2,'Color',[0 0 1]);

% Create ylabel
ylabel('True Positive Rate');

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('All ROC');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0 1]);
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'DataAspectRatio',[1 1 1]);
% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

